abbr -a l "exa -alg --icons --colour=never"
abbr -a ld "exa -alg --icons -d */ --colour=never"
#abbr -a ld "du -hs */"
# clear cache
abbr -a clear_cache "sync; echo 1 > /proc/sys/vm/drop_caches"
abbr -a rb "sudo reboot"
abbr -a lblk "lsblk -o +fstype,label,uuid,partuuid"
abbr -a umo "sudo umount"
abbr -a mo "sudo mount"
abbr -a i "sudo apt-get install "
abbr -a s "apt-cache search"
abbr -a u "sudo apt update && sudo apt upgrade"
abbr -a .. "cd .."
abbr -a ... "cd ..."
abbr -a .... "cd ...."
abbr -a ..... "cd ....."
abbr -a 1 "cd -"
abbr -a 2 "cd -2"
abbr -a 3 "cd -3"
abbr -a 4 "cd -4"
abbr -a wpli "~/git/ho-updates/wplocalinstall.sh -pk "
abbr -a wpup "~/git/ho-updates/wpupdate.sh"
abbr -a wget "wget --no-check-certificate"
abbr -a x "exit"
abbr -a u "date"
set pw '9v908oZ\$'
alias os="sshpass -p $pw ssh nickel.dnsupdater.de"
abbr -a dcr "docker container run --it -d -p 80:80"
abbr -a ul "sudo mount --bind  /mnt/wsl/web/ /var/www/html/arbeit/ && sudo service apache2 start  && sudo service mysql start"
abbr -a dl "sudo service apache2 stop  && sudo service mysql stop"
abbr -a sl "sudo service apache2 status  && sudo service mysql status"
abbr -a op "sudo ss -tulpn | grep LISTEN"
abbr -a gcl "git clone"
abbr -a re ' set WW "aurahotel" "beans-and-books" "input-inklusiv" "eca" "biko-bayern" "weclimb" "rollwagerl" "rollstuhlkurier" "sbs" "SBZ" "pfarrverband-gruenwald-relaunch" "seniorenstift-neuhausen" "netzwerkfrauen" "pp-news" "pp-pfennigcheckin" "Pfennigparade.de" "Pfennigfenster" "karriere.pfennigparade.de"  "wkm-reha-marketing" "teealternative.de" "neuronetzwerk" "wkm-reha-marketing" "wp-starter"'
abbr -a wpmod "~/git/ho-updates/wpmod.sh -c"
